Repository novitai/skycompress, pull requests merged in 2023-10, with the labels that each got.

#1 Repo rename chaos
  .gitignore
  README.md
  dist/image_compression-0.1.0-py3-none-any.whl
  dist/image_compression-0.1.0.tar.gz
  pyproject.toml
  skycompress/__init__.py
  skycompress/compress_image.py
Labels: enhancement

#2 FIX: fov request corrupted image fix
  skycompress/compress_image.py
Labels: bug

#4 ADD: update init py to reach compress_image without duplication
  skycompress/__init__.py
Labels: enhancement

#5 ADD: new method call instruction
  README.md
Labels: documentation

#9 RM: color formats
  .github/workflows/lint_type_sort.yml
  .github/workflows/python-package.yml
  pyproject.toml
  skycompress/compress_image.py
  tests/test_compression.py
Labels: invalid
